n = int(input('Informe um numero: '))
print('----------------')
print('{} x {:2} = {:2}'.format(n, 1, 1*n))
print('{} x {:2} = {:2}'.format(n, 2, 2*n))
print('{} x {:2} = {:2}'.format(n, 3, 3*n))
print('{} x {:2} = {:2}'.format(n, 4, 4*n))
print('{} x {:2} = {:2}'.format(n, 5, 5*n))
print('{} x {:2} = {:2}'.format(n, 6, 6*n))
print('{} x {:2} = {:2}'.format(n, 7, 7*n))
print('{} x {:2} = {:2}'.format(n, 8, 8*n))
print('{} x {:2} = {:2}'.format(n, 9, 9*n))
print('{} x {:2} = {:2}'.format(n, 10, 10*n))
print('----------------')
